name: demo
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

# Dependencies specify other packages that your package needs in order to work.
dependencies:
  flutter:
    sdk: flutter
  get: 4.6.1
  http: ^0.13.4
  json_annotation: ^4.4.0
  intl: ^0.17.0
  image_picker: ^0.8.4
  syncfusion_flutter_charts: ^19.4.56
  url_launcher: ^6.0.20
  flutter_svg: ^0.21.0-nullsafety.0
  flutter_barcode_scanner: ^2.0.0
  cupertino_icons: ^1.0.2
  age_calculator: ^1.0.0
  flutter_speed_dial: ^3.0.5
  supabase_flutter: ^0.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.0.0
  json_serializable: ^6.0.0

  flutter_lints: ^1.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/NutriAI.png
    - assets/greenprofile.jpg
    - assets/Iherb_logo.jpeg
    - assets/logos.json
    - assets/Login_design.png
    - assets/forkspoon.png

  fonts:
    - family: CustomIcon
      fonts:
        - asset: assets/fonts/CustomIcon.ttf
